@base=http://localhost:8080

### Chat
POST {{base}}/api/v1/chat
Accept: text/plain
Content-Type: application/json

{
  "query": "초과근로 승인 기준",
  "topK": 10,
  "label": "compensation"
}

### Chat stream
POST {{base}}/api/v1/chat/stream
Accept: text/event-stream
Content-Type: application/json

{
  "query": "초과근로 승인 기준",
  "topK": 10,
  "label": "compensation"
}



### Ingest vectors
POST {{base}}/api/v1/vectors
Accept: application/json
Content-Type: application/json


### Search vectors
POST {{base}}/api/v1/vectors/search
Accept: application/json
Content-Type: application/json

{
  "query": "제품 A에 대한 평가는?",
  "topK": 5
}
